DEEP LEARNING -> Bank Customer Churn Modeling

This project has 2 case studies. The first case study (described below - 30 points) covers concepts taught in Part 1 (first 8 hours of Neural networks basics).

1st case study - Project 1:

The case study is from an open source dataset from Kaggle. 

Link to the Kaggle project site:

https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling (Links to an external site.)Links to an external site.

Given a Bank customer, can we build a classifier which can determine whether they will leave or not using Neural networks?

Data file - bank.csvView in a new window

 

The points distribution for this case is as follows:

Read the dataset
Drop the columns which are unique for all users like IDs (2.5 points)
Distinguish the feature and target set (2.5 points)
Divide the data set into Train and test sets
Normalize the train and test data (2.5 points)
Initialize & build the model (10 points)
Optimize the model (5 points)
Predict the results using 0.5 as a threshold (5 points)
Print the Accuracy score and confusion matrix (2.5 points)

1. Read the dataset 

In [1]:
import tensorflow as tf
tf.set_random_seed(42)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras


Using TensorFlow backend.


In [2]:
tf.__version__

'1.15.0-rc3'

In [3]:
from google.colab import files
file=files.upload()
bank_csv=pd.read_csv('bank.csv')

In [4]:
bank_csv.head(3)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1

[3 rows x 14 columns]

In [5]:
bank_csv.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
bank_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
bank_csv.CustomerId.nunique()

10000

2. Drop the columns which are unique for all users like IDs (2.5 points)

In [0]:
bank_csv.drop(['CustomerId','RowNumber','Surname'],axis=1,inplace=True)

In [9]:
bank_csv.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

3. Distinguish the feature and target set (2.5 points) 

In [0]:
X = bank_csv.iloc[:, 0:10].values
y = bank_csv.iloc[:, 10].values

In [11]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [12]:
y[0]

1

In [0]:
#Geography and Gender Column needs to be encoded
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [0]:
le1 = LabelEncoder()
X[:, 2] = le1.fit_transform(X[:, 2])

In [16]:
onehotencoder = OneHotEncoder(categorical_features = [1])
feature = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
X[0]

array([0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [18]:
y[0]

1

4. Divide the data set into Train and test sets 

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3,random_state=1)

5. Normalize the train and test data (2.5 points)

In [0]:
from sklearn.preprocessing import Normalizer

In [0]:
transformer = Normalizer()
Xtrain = transformer.fit_transform(Xtrain)
Xtest = transformer.fit_transform(Xtest)

In [23]:
Xtrain[0]

array([0.00000000e+00, 0.00000000e+00, 1.76451673e-03, 3.81517130e-04,
       0.00000000e+00, 9.53792825e-05, 4.76896413e-05, 0.00000000e+00,
       9.99998365e-01])

In [24]:
Xtest[0]

array([0.00000000e+00, 1.03031929e-05, 4.84250068e-04, 2.06063859e-05,
       0.00000000e+00, 2.06063859e-05, 1.03031929e-05, 1.03031929e-05,
       9.99999882e-01])

In [25]:
print(Xtrain.shape)
print(Xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(7000, 9)
(3000, 9)
(7000,)
(3000,)


6. Initialize & build the model (10 points) 

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 2 Outputs after applying softmax
model.add(tf.keras.layers.Dense(2, activation='relu'))


In [0]:
#Build the graph
#Add 1st hidden layer
model.add(tf.keras.layers.Dense(6, activation='relu'))

#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(6, activation='relu'))


#Add OUTPUT layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [0]:
# Compiling the Neural Network
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [60]:
#Execute the Graph
model.fit(Xtrain, ytrain, validation_data=(Xtest, ytest),epochs=100,batch_size=10)

Train on 7000 samples, validate on 3000 samples
Epoch 1/100
7000/7000 [==============================] - 2s 259us/sample - loss: 0.6207 - acc: 0.7896 - val_loss: 0.5708 - val_acc: 0.7910
Epoch 2/100
7000/7000 [==============================] - 1s 205us/sample - loss: 0.5395 - acc: 0.7986 - val_loss: 0.5275 - val_acc: 0.7910
Epoch 3/100
7000/7000 [==============================] - 1s 212us/sample - loss: 0.5121 - acc: 0.7986 - val_loss: 0.5154 - val_acc: 0.7910
Epoch 4/100
7000/7000 [==============================] - 1s 201us/sample - loss: 0.5046 - acc: 0.7986 - val_loss: 0.5129 - val_acc: 0.7910
Epoch 5/100
7000/7000 [==============================] - 1s 211us/sample - loss: 0.5028 - acc: 0.7986 - val_loss: 0.5126 - val_acc: 0.7910
Epoch 6/100
7000/7000 [==============================] - 1s 202us/sample - loss: 0.5025 - acc: 0.7986 - val_loss: 0.5127 - val_acc: 0.7910
Epoch 7/100
7000/7000 [==============================] - 1s 212us/sample - loss: 0.5025 - acc: 0.7986 - val_loss: 0.51

In [0]:
#loss is at 50% with 79.86% accuracy 

7. Optimize the model (5 points) 

In [0]:
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)
model.compile(optimizer=sgd_optimizer, loss='mse')

In [62]:
#Execute the Graph
model.fit(Xtrain, ytrain, validation_data=(Xtest, ytest),epochs=100,batch_size=10)

Train on 7000 samples, validate on 3000 samples
Epoch 1/100
7000/7000 [==============================] - 2s 264us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 2/100
7000/7000 [==============================] - 1s 176us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 3/100
7000/7000 [==============================] - 1s 172us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 4/100
7000/7000 [==============================] - 1s 173us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 5/100
7000/7000 [==============================] - 1s 170us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 6/100
7000/7000 [==============================] - 1s 173us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 7/100
7000/7000 [==============================] - 1s 174us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 8/100
7000/7000 [==============================] - 1s 174us/sample - loss: 0.1609 - val_loss: 0.1654
Epoch 9/100
7000/7000 [==============================] - 1s 174us/sample - loss: 0.1609 - val_lo

In [0]:
#loss is at 16%, there is loss reduction by 34%

8. Predict the results using 0.5 as a threshold (5 points) 

In [0]:
Ypred = model.predict(Xtest)

In [0]:
#Model prediction
prediction = model.predict(Xtest)
Ypred = (Ypred > 0.5)

In [66]:
#Print prediction
print(prediction)

[[0.20238924]
 [0.20238924]
 [0.20238924]
 ...
 [0.20238924]
 [0.20238924]
 [0.20238924]]


In [67]:
ytest[0]

0

9. Print the Accuracy score and confusion matrix (2.5 points)

In [68]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, Ypred)
print(cm)

[[2373    0]
 [ 627    0]]


In [69]:
# Visualizing confusion matrix
pos, neg = cm
tp, fp = pos
fn, tn = neg
print('True Positives:', tp)
print('True Negatives:', tn)
print('False Positives:', fp)
print('False Negatives:', fn)

True Positives: 2373
True Negatives: 0
False Positives: 0
False Negatives: 627


In [70]:

# Accuracy rate of confusion matrix
print('Accuracy:', (tp+tn)/(tp+tn+fp+fn))

Accuracy: 0.791


In [0]:
#Accuracy is 79%